version: '3'
services:

  frontend:
    extends:
      file: frontend/docker-compose.yml
      service: frontend

  backend:
    extends:
      file: backend/docker-compose.yml
      service: backend

  mongodb:
    extends:
      file: mongodb/docker-compose.yml
      service: mongodb
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: