version: '3'
services:

  mongodb:
    image: mongo
    container_name: mongodb
    env_file:
      - .env.mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: